//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Resource.rc
//
#define IDB_BITMAP_MAIN                 1000
#define IDB_BITMAP_VIEW_TOOLBAR         1001
#define IDR_MENU_MAIN                   2000
#define IDD_DIALOGBAR_CONTROL           3000
#define IDD_DIALOG_SELECT_TEXTURE       3001
#define IDD_DIALOG_SETTINGS_WALL        3002
#define IDD_DIALOG_SETTINGS_SECTOR      3003
#define IDD_DIALOG_TEXTURE_FOLLOW       3004
#define ID_MENU_FILE_LOAD               4000
#define ID_MENU_FILE_SAVE               4001
#define ID_MENU_FILE_CLEARMAP           4002
#define ID_MENU_FILE_RESET              4003
#define ID_MENU_FILE_EXIT               4004
#define ID_MENU_WINDOW_MAINPANEL        4005
#define ID_MENU_WINDOW_MAIN_PANEL       4006
#define ID_MENU_WINDOW_CONTROL_PANEL    4007
#define ID_MENU_WINDOW_VIEW_PANEL       4008
#define IDD_COMBOBOX_GRIDSIZE           5000
#define IDC_STATIC_DIALOGBAR_CONTROL_CURSOR_X 5001
#define IDC_STATIC_DIALOGBAR_CONTROL_CURSOR_Y 5002
#define IDC_BUTTON_DIALOGBAR_CONTROL_DELETE 5003
#define ID_BUTTON_TOOLBAR_VIEW_SCALE_PLUS 5004
#define ID_BUTTON_TOOLBAR_VIEW_SCALE_MINUS 5005
#define ID_BUTTON_TOOLBAR_VIEW_BINDING  5006
#define ID_BUTTON_TOOLBAR_MAIN_CREATE_WALL 5007
#define ID_BUTTON_TOOLBAR_MAIN_CREATE_FRONTIER 5008
#define ID_BUTTON_TOOLBAR_MAIN_CREATE_SECTOR 5009
#define ID_BUTTON_TOOLBAR_MAIN_FRONTIER_SELECT 5010
#define ID_BUTTON_TOOLBAR_MAIN_WALL_SELECT 5011
#define ID_BUTTON_TOOLBAR_MAIN_SECTOR_SELECT 5012
#define IDC_SCROLL_DIALOG_SELECT_TEXTURE_VERTICAL 5013
#define ID_BUTTON_TOOLBAR_MAIN_SET_PLAYER_POSITION 5014
#define IDC_SCROLL_DIALOG_SELECT_TEXTURE_HORIZONTAL 5015
#define IDC_BUTTON_DIALOG_SELECT_TEXTURE_OK 5016
#define IDC_BUTTON_DIALOG_SETTINGS_WALL_COPY_TO_DOWN 5017
#define IDC_BUTTON_DIALOG_SETTINGS_WALL_COPY_TO_UP 5018
#define IDC_BUTTON_DIALOG_SELECT_TEXTURE_CANCEL 5019
#define IDC_BUTTON_DIALOG_SETTINGS_WALL_CHANGETEXTURE_UP 5020
#define IDC_BUTTON_DIALOG_SETTINGS_WALL_CHANGETEXTURE_DOWN 5021
#define IDC_BUTTON_DIALOG_SETTINGS_WALL_OK 5022
#define IDC_BUTTON_DIALOG_SETTINGS_WALL_CANCEL 5023
#define IDC_BUTTON_DIALOG_SETTINGS_WALL_ANIMATE_UP 5024
#define IDC_BUTTON_DIALOG_SETTINGS_WALL_ANIMATE_DOWN 5025
#define IDC_BUTTON_DIALOG_SETTINGS_SECTOR_CHANGETEXTURE_DOWN 5026
#define IDC_BUTTON_DIALOG_SETTINGS_SECTOR_CHANGETEXTURE_UP 5027
#define IDC_EDIT_DIALOG_SETTINGS_SECTOR_DOWN_LEVEL 5028
#define IDC_EDIT_DIALOG_SETTINGS_SECTOR_UP_LEVEL 5029
#define IDC_BUTTON_DIALOG_SETTINGS_SECTOR_OK 5030
#define IDC_BUTTON_DIALOG_SETTINGS_SECTOR_CANCEL 5031
#define IDC_BUTTON_DIALOG_SETTINGS_SECTOR_ANIMATE_DOWN 5032
#define IDC_BUTTON_DIALOG_SETTINGS_SECTOR_ANIMATE_UP 5033
#define IDC_SCROLLBAR_DIALOG_TEXTURE_FOLLOW_LIST 5034
#define IDC_EDIT_DIALOG_SETTINGS_SECTOR_BASE_LIGHTING 5035
#define IDC_BUTTON_DIALOG_TEXTURE_FOLLOW_ADD 5036
#define IDC_EDIT_DIALOG_SETTINGS_SECTOR_BASE_LIGHTING_TIME 5037
#define IDC_BUTTON_DIALOG_TEXTURE_FOLLOW_DELETE 5038
#define IDC_EDIT_DIALOG_SETTINGS_SECTOR_MAX_LIGHTING_TIME 5039
#define IDC_BUTTON_DIALOG_TEXTURE_FOLLOW_REPEAT 5040
#define IDC_EDIT_DIALOG_SETTINGS_SECTOR_LABEL 5041
#define IDC_BUTTON_DIALOG_TEXTURE_FOLLOW_CLEAR 5042
#define IDC_EDIT_DIALOG_SETTINGS_SECTOR_WORKING_LEVEL 5043
#define IDC_BUTTON_DIALOG_TEXTURE_FOLLOW_CANCEL 5044
#define IDC_BUTTON_DIALOG_SETTINGS_SECTOR_COPY_TO_FLOW 5045
#define IDC_BUTTON_DIALOG_TEXTURE_FOLLOW_OK 5046
#define IDC_BUTTON_DIALOG_SETTINGS_SECTOR_COPY_TO_FLOOR 5047
#define IDC_RADIOBUTTON_DIALOG_TEXTURE_FOLLOW_CYCLES 5048
#define IDC_RADIOBUTTON_DIALOG_TEXTURE_FOLLOW_ZIGZAG 5049
#define IDC_RADIOBUTTON_DIALOG_TEXTURE_FOLLOW_DISABLE 5050
#define IDC_BUTTON_DIALOGBAR_CONTROL_SECTOR_SETTINGS 5051
#define IDC_RADIOBUTTON_DIALOG_SETTINGS_SECTOR_LIGHTING_MODE_DAWNING_SUNDOWN 5052
#define IDC_BUTTON_DIALOGBAR_CONTROL_WALL_SETTINGS 5053
#define IDC_BUTTON_DIALOGBAR_CONTROL_EDIT 5054
#define ID_MENU_FILE_EXPORT_BSP         20000
#define ID_MENU_FILE_EXPORT_PORTAL      20001
#define ID_MENU_FILE_IMPORT_TXT         20002
#define IDC_RADIOBUTTON_DIALOG_SETTINGS_SECTOR_LIGHTING_MODE_STATIC 30000
#define IDC_RADIOBUTTON_DIALOG_SETTINGS_SECTOR_LIGHTING_MODE_FLASH 30001
#define IDC_RADIOBUTTON_DIALOG_SETTINGS_SECTOR_LIGHTING_MODE_RANDOM_FLASH 30002
#define IDC_COMBO_DIALOG_SETTINGS_SECTOR_TYPE 30003
#define IDC_CHECK_DIALOG_SETTINGS_WALL_SWITCH 30004
#define IDC_EDIT_DIALOG_SETTINGS_WALL_SWITCH_LABEL 30005
#define IDC_CHECK_DIALOG_SETTINGS_ANTIGRAVITATION 30006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        10000
#define _APS_NEXT_COMMAND_VALUE         20003
#define _APS_NEXT_CONTROL_VALUE         30008
#define _APS_NEXT_SYMED_VALUE           40000
#endif
#endif
